import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'All - In - One - Shopping - Mart',
  description: 'Generated by Rabees Hussain',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-blue-50">
        {children}
      </body>
    </html>
  )
}
